#!/usr/bin/env bash

system_type=$(uname -s)

has_command () { command -v "$1" > /dev/null 2>&1 ; }

mkdir -p $HOME/bin

if [ $system_type = "linux" ] && has_command apt ; then
  # Debian/Ubuntu
  # Note: no kdiff3; that pulls in all the GUI libs
  sudo apt install -y zsh curl git less vim bat eza fzf fd-find git-delta ripgrep
fi

if [ $system_type = "linux" ] && has_command dnf ; then
  # Fedora/Rocky
  # Note: no kdiff3; that pulls in all the GUI libs
  sudo dnf install -y zsh curl git less vim bat eza fd-find git-delta ripgrep
fi

if has_command brew; then
  brew install -q bat eza fzf fd git-delta kdiff3 ripgrep
fi

# fzf
if ! has_command fzf; then
  git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
  ~/.fzf/install
fi

# git graph
if ! has_command git-graph; then
  if [[ $system_type =~ "[Ll]inux" ]]; then
     url="https://github.com/mlange-42/git-graph/releases/download/0.5.3/git-graph-0.5.3-linux-amd64.tar.gz"
  elif [[ $system_type == "Darwin" ]]; then
     url="https://github.com/mlange-42/git-graph/releases/download/0.5.3/git-graph-0.5.3-macos-amd64.tar.gz"
  else # [ $system_type = "Windows" ]
     url="https://github.com/mlange-42/git-graph/releases/download/0.5.3/git-graph-0.5.3-windows-amd64.tar.gz"
  fi
  curl -sL "$url" | tar zx -C $HOME/bin/ # single executable, untar directly
fi

# "zplug" zsh plugin manager
curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
